#:schema node_modules/wrangler/config-schema.json
name = "medical-questionnaire"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "medical-db"
database_id = "39a37231-3d65-4cf3-8569-713429bde82d"
